languageCode = "en-us"
title = "Naresh Mehta"
baseurl = "/"
theme = "hugo-geo"
relativeURLs = true
disqusShortname = "wolverine2k"
paginate = 5

[taxonomies]
	tag = "tags"
	tutorial = "tutorials"

[params]
	# Render the rotating globe in the sidebar
	showglobe = true

	# Include favicon
	favicon = "favicon.ico"

	# Google Analytics
	#analytics = "SHORT-CODE-HERE"

	# Email (optional)
	email = "naresh.mehta@gmail.com"

	# Header Title for the main page
	header = "My rantings on events around the world!"

	# Sidebar profile picture
	#profilepic = "avatars1.githubusercontent.com/u/1121738?v=3&s=460"
	profilepic = "scontent-arn2-1.xx.fbcdn.net/v/t31.0-8/10914878_922215147818818_5862894609207655706_o.jpg?oh=870d924f4e2e85ecd9d0d2f436b2e04a&oe=59A92534"

	# Title/subtitle for the sidebar
	title = "Naresh Mehta"
	subtitle = "Ideas analyzed logically to make sense & grow upon..."

  [[params.socialbuttons]]
    faicon = "twitter"
    url = "https://twitter.com/wolverine2k"

  [[params.socialbuttons]]
    faicon = "github"
    url = "https://github.com/wolverine2k"

  [[params.socialbuttons]]
    faicon = "bitbucket"
    url = "https://bitbucket.com/wolverine2k"

  [[params.socialbuttons]]
    faicon = "gitlab"
    url = "https://gitlab.com/wolverine2k"

  [[params.socialbuttons]]
    faicon = "linkedin"
    url = "https://se.linkedin.com/in/nareshmehta"

  [[params.socialbuttons]]
    faicon = "stack-overflow"
    url = "http://stackoverflow.com/users/5599099"

  [[params.socialbuttons]]
    faicon = "paypal"
    url = "http://paypal.me/NareshMehta"

  [[params.socialbuttons]]
    faicon = "facebook"
    url = "https://facebook.com/wolverine2k"

  [[params.socialbuttons]]
    faicon = "google-plus"
    url = "https://plus.google.com/107609468931427204531"

  [[params.socialbuttons]]
    faicon = "instagram"
    url = "http://instagram.com/wolverine2k"

  [[params.socialbuttons]]
    faicon = "youtube"
    url = "https://www.youtube.com/user/wolverine2k1"

#  [[params.socialbuttons]]
#    faicon = "skype"
#    url = "skype:wolverine2k?userinfo"